# ==================================================
# KIOSK PERFORMANCE CONFIGURATION
# Purpose: Configurable performance settings for kiosk modes
# ==================================================

performance:
  # Auto-Refresh Settings
  refresh:
    enabled: true
    interval_seconds: 120  # 2 minutes default
    max_retries: 3
    smooth_reload: true    # Use smooth overlay instead of hard reload
    ajax_refresh: true     # Try AJAX refresh first
    preload_content: true  # Preload next refresh
    
  # Memory Management
  memory:
    cleanup_enabled: true
    cleanup_interval_minutes: 5
    max_memory_mb: 100
    gc_threshold_mb: 150
    auto_reload_on_memory_pressure: true
    
  # Frame Rate & Rendering
  rendering:
    target_fps: 60
    performance_threshold_fps: 30
    gpu_acceleration: true
    animation_optimization: true
    viewport_culling: true  # Pause animations outside viewport
    
  # Font Loading & Rendering  
  fonts:
    display_mode: "swap"     # swap, block, fallback, optional
    preload_critical: true   # Preload critical fonts
    font_smoothing: "antialiased"  # antialiased, auto, none
    high_dpi_optimization: true
    
  # Network & Caching
  network:
    smart_caching: true
    cache_duration_seconds: 60
    preload_timing_seconds: 10  # Preload X seconds before refresh
    offline_fallback: true
    
  # Touch & Interaction
  touch:
    optimized_targets: true  # Larger touch targets
    hover_disabled_on_touch: true
    smooth_scrolling: true
    tap_highlight_color: "rgba(0, 168, 107, 0.3)"
    
  # Display Size Optimizations
  display:
    auto_scaling: true
    large_display_threshold_px: 1920
    ultra_display_threshold_px: 2560
    font_scale_large: 1.2
    font_scale_ultra: 1.5
    container_queries: true  # Use CSS container queries
    
  # Debug & Monitoring
  monitoring:
    performance_logging: true
    fps_monitoring: true
    memory_monitoring: true
    error_reporting: true
    console_metrics: true   # Log performance metrics to console
    
  # Accessibility
  accessibility:
    respect_reduced_motion: true
    high_contrast_support: true
    focus_management: true
    screen_reader_optimization: true
    
# Thai Language Specific Optimizations
thai_optimizations:
  font_loading:
    unicode_range_optimization: true  # Load only Thai characters
    fallback_fonts: ["Noto Sans Thai", "Leelawadee UI", "Tahoma"]
    line_height_adjustment: 1.6      # Thai text needs more space
    word_break: "break-word"         # Thai doesn't use spaces
    
  rendering:
    text_rendering: "optimizeLegibility"
    font_feature_settings: ["kern", "liga", "calt"]
    webkit_font_smoothing: "antialiased"

# Feature Toggles (Environment-based)
features:
  kiosk_performance_manager: true
  flicker_free_refresh: true
  memory_optimization: true
  font_optimization: true
  touch_optimization: true
  
# Environment-specific Settings
environments:
  development:
    performance:
      monitoring:
        performance_logging: true
        console_metrics: true
      refresh:
        interval_seconds: 30  # Faster refresh in dev
        
  production:
    performance:
      monitoring:
        performance_logging: false
        console_metrics: false
      refresh:
        interval_seconds: 120
        
  kiosk:
    performance:
      refresh:
        interval_seconds: 300  # Slower refresh for kiosk (5 min)
      memory:
        max_memory_mb: 200     # More memory for kiosk displays
      display:
        auto_scaling: true
        
# Security Settings for Performance Features
security:
  ajax_refresh:
    csrf_protection: true
    rate_limiting: true
    max_requests_per_minute: 30
    
  caching:
    secure_headers: true
    no_cache_sensitive_data: true
    
  error_handling:
    sanitize_error_messages: true
    log_security_events: true